// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiSO47wuprY2Y85tIo5mq1bUZVRHQUUsY',
    appId: '1:84905058581:web:e1ed3357b113b63fe2491c',
    messagingSenderId: '84905058581',
    projectId: 'mfu-restaurant-comments',
    authDomain: 'mfu-restaurant-comments.firebaseapp.com',
    storageBucket: 'mfu-restaurant-comments.firebasestorage.app',
    measurementId: 'G-BM35HS74GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcxTYFVVe0qJFAPaZFq7CK42xqpTWMsQQ',
    appId: '1:84905058581:android:401ad48bde87b21fe2491c',
    messagingSenderId: '84905058581',
    projectId: 'mfu-restaurant-comments',
    storageBucket: 'mfu-restaurant-comments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPuKYZG2J6ydmz1TJZJtbBLbuxpXuZYpw',
    appId: '1:84905058581:ios:ed931832ab24e7f6e2491c',
    messagingSenderId: '84905058581',
    projectId: 'mfu-restaurant-comments',
    storageBucket: 'mfu-restaurant-comments.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPuKYZG2J6ydmz1TJZJtbBLbuxpXuZYpw',
    appId: '1:84905058581:ios:ed931832ab24e7f6e2491c',
    messagingSenderId: '84905058581',
    projectId: 'mfu-restaurant-comments',
    storageBucket: 'mfu-restaurant-comments.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiSO47wuprY2Y85tIo5mq1bUZVRHQUUsY',
    appId: '1:84905058581:web:9f0defdcec86abd8e2491c',
    messagingSenderId: '84905058581',
    projectId: 'mfu-restaurant-comments',
    authDomain: 'mfu-restaurant-comments.firebaseapp.com',
    storageBucket: 'mfu-restaurant-comments.firebasestorage.app',
    measurementId: 'G-BE98FMR1HD',
  );
}
